import { ConfigManifestEntry, ConfigManifestEntryType } from '@sofie-automation/blueprints-integration'
import { AudioSourceType, SourceType, VisionMixerType } from './helpers/config'

export const studioConfigManifest: ConfigManifestEntry[] = [
	{
		id: 'visionMixerType',
		name: 'Vision mixer type',
		description: 'Atem or VMix',
		type: ConfigManifestEntryType.ENUM,
		required: true,
		defaultVal: VisionMixerType.Atem,
		options: [VisionMixerType.Atem, VisionMixerType.VMix],
	},
	{
		id: 'atemSources',
		name: 'Atem Sources',
		description: 'Description of Atem inputs i.e. cameras, remotes etc.',
		type: ConfigManifestEntryType.TABLE,
		required: true,
		defaultVal: [],
		columns: [
			{
				id: 'input',
				name: 'Input',
				description: 'Input number on the atem, see https://atem.julusian.dev/enums#videosource',
				type: ConfigManifestEntryType.NUMBER,
				required: true,
				defaultVal: 0,
				rank: 1,
			},
			{
				id: 'type',
				name: 'Type',
				description: 'Input type',
				type: ConfigManifestEntryType.ENUM,
				options: [SourceType.Camera, SourceType.Remote, SourceType.MediaPlayer, SourceType.Graphics],
				required: true,
				defaultVal: 'camera',
				rank: 2,
			},
		],
	},
	{
		id: 'atemOutputs',
		name: 'Atem Outputs',
		description: 'Description of Atem outputs / auxes',
		type: ConfigManifestEntryType.TABLE,
		required: true,
		defaultVal: [],
		columns: [
			{
				id: 'output',
				name: 'Output',
				description: 'Aux number on the atem',
				type: ConfigManifestEntryType.NUMBER,
				required: true,
				defaultVal: 1,
				rank: 1,
			},
			{
				id: 'source',
				name: 'Source',
				description: 'Source number, see https://atem.julusian.dev/enums#videosource',
				type: ConfigManifestEntryType.NUMBER,
				required: true,
				defaultVal: 1,
				rank: 2,
			},
		],
	},
	{
		id: 'vmixSources',
		name: 'VMix Sources',
		description: 'Description of vmix inputs i.e. cameras, remotes etc.',
		type: ConfigManifestEntryType.TABLE,
		required: true,
		defaultVal: [],
		columns: [
			{
				id: 'input',
				name: 'Input',
				description: 'Input number for the vmix source',
				type: ConfigManifestEntryType.NUMBER,
				required: true,
				defaultVal: 0,
				rank: 1,
			},
			{
				id: 'type',
				name: 'Type',
				description: 'Input type',
				type: ConfigManifestEntryType.ENUM,
				options: [SourceType.Camera, SourceType.Remote, SourceType.MediaPlayer, SourceType.Graphics],
				required: true,
				defaultVal: 'camera',
				rank: 2,
			},
		],
	},
	{
		id: 'sisyfosSources',
		name: 'Sisyfos Sources',
		description: 'Description of Sisyfos channels',
		type: ConfigManifestEntryType.TABLE,
		required: true,
		defaultVal: [],
		columns: [
			{
				id: 'source',
				name: 'Source',
				description: 'Channel number of the sisyfos channel',
				type: ConfigManifestEntryType.INT,
				required: true,
				defaultVal: 0,
				rank: 1,
				zeroBased: true,
			},
			{
				id: 'type',
				name: 'Type',
				description: 'Input type',
				type: ConfigManifestEntryType.ENUM,
				options: [AudioSourceType.Host, AudioSourceType.Guest, AudioSourceType.Remote, AudioSourceType.Playback],
				required: true,
				defaultVal: 'host',
				rank: 2,
			},
		],
	},
	{
		id: 'previewRenderer',
		name: 'Preview Renderer',
		description: 'Graphics preview renderer URL',
		type: ConfigManifestEntryType.STRING,
		required: false,
		defaultVal: '',
	},
	{
		id: 'casparcgLatency',
		name: 'CasparCG Latency',
		description: 'Delay in ms before SDI signal hits the mixer',
		type: ConfigManifestEntryType.NUMBER,
		required: false,
		defaultVal: 160,
	},
]
