import { compileFromFile } from 'json-schema-to-typescript'
import * as fs from 'fs/promises'
;(async function main() {
	const BANNER =
		'/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run "yarn generate-schema-types" to regenerate this file.\n */\n'

	const PrettierConf = JSON.parse(
		await fs.readFile('../../node_modules/@sofie-automation/code-standard-preset/.prettierrc.json')
	)

	await fs.mkdir('src/$schemas/generated', { recursive: true })

	// convert showStyle-config options
	try {
		const schema = await compileFromFile('./src/$schemas/main-showstyle-config.json', {
			additionalProperties: false,
			style: PrettierConf,
			bannerComment: '',
			enableConstEnums: false,
		})

		await fs.writeFile('./src/$schemas/generated/main-showstyle-config.ts', BANNER + '\n' + schema)
	} catch (e) {
		console.error('Error while generating main-showstyle-config.json, continuing...')
		console.error(e)
	}

	// convert studio-config options
	try {
		const schema = await compileFromFile('./src/$schemas/main-studio-config.json', {
			additionalProperties: false,
			style: PrettierConf,
			bannerComment: '',
			enableConstEnums: false,
		})

		await fs.writeFile('./src/$schemas/generated/main-studio-config.ts', BANNER + '\n' + schema)
	} catch (e) {
		console.error('Error while generating main-studio-config.json, continuing...')
		console.error(e)
	}
})().catch(console.error)
