import { SourceType, StudioConfig, VisionMixerDevice } from '../../../base/studio/helpers/config.js'

export const DemoStudioConfig: StudioConfig = {
	previewRenderer: 'sofie',
	ografBaseUrl: 'http://localhost:8080',
	obsMediaBasePath: '',
	casparcgLatency: 0,
	visionMixer: {
		type: VisionMixerDevice.Atem,
		host: '0.0.0.0',
		port: 9910,
		deviceId: 'atem0',
	},
	audioMixer: {
		host: 'localhost',
		port: 1176,
		deviceId: 'sisyfos0',
	},
	casparcg: {
		host: 'localhost',
		port: 5250,
	},
	sisyfosSources: {},
	vmixSources: {},
	obsSources: {},
	atemOutputs: {},
	atemSources: {
		camera1: { input: 1, type: SourceType.Camera },
		camera2: { input: 2, type: SourceType.Camera },
		camera3: { input: 3, type: SourceType.Camera },
		camera4: { input: 4, type: SourceType.Camera },
		remote1: { input: 5, type: SourceType.Remote },
		remote2: { input: 6, type: SourceType.Remote },
		mediaplayer: { input: 7, type: SourceType.MediaPlayer },
		graphics: { input: 8, type: SourceType.Graphics },
	},
}

export const DemoOBSStudioConfig: StudioConfig = {
	previewRenderer: 'sofie',
	ografBaseUrl: 'http://localhost:8080',
	obsMediaBasePath: '',
	obsDownstreamKeyerSourceId: 'dsk',
	obsAbMediaPlayerSourceIds: ['mediaplayer1', 'mediaplayer2'],
	obsEffectsMediaPlayerSourceId: 'mediaplayer3',
	casparcgLatency: 0,
	visionMixer: {
		type: VisionMixerDevice.OBS,
		host: 'localhost',
		port: 4455,
		deviceId: 'obs0',
		password: '',
	},
	audioMixer: {
		host: 'localhost',
		port: 1176,
		deviceId: 'sisyfos0',
	},
	casparcg: {
		host: 'localhost',
		port: 5250,
	},
	sisyfosSources: {},
	vmixSources: {},
	atemOutputs: {},
	atemSources: {},
	obsSources: {
		camera1: { sceneName: 'CAM 1', sourceName: 'CAM 1', type: SourceType.Camera },
		camera2: { sceneName: 'CAM 2', sourceName: 'CAM 2', type: SourceType.Camera },
		camera3: { sceneName: 'CAM 3', sourceName: 'CAM 3', type: SourceType.Camera },
		remote1: {
			sceneName: 'EXT 1',
			sourceName: 'EXT 1',
			audioSourceName: 'EXT 1',
			type: SourceType.Remote,
		},
		remote2: {
			sceneName: 'EXT 2',
			sourceName: 'EXT 2',
			audioSourceName: 'EXT 2',
			type: SourceType.Remote,
		},
		mediaplayer1: {
			sceneName: 'Media player 1',
			sourceName: 'Player 1',
			audioSourceName: 'Player 1',
			type: SourceType.MediaPlayer,
		},
		mediaplayer2: {
			sceneName: 'Media player 2',
			sourceName: 'Player 2',
			audioSourceName: 'Player 2',
			type: SourceType.MediaPlayer,
		},
		mediaplayer3: {
			sceneName: 'Media player 3',
			sourceName: 'Player 3',
			audioSourceName: 'Player 3',
			type: SourceType.MediaPlayer,
		},
		dve: { sceneName: 'DVE 2BOX', sourceName: 'DVE 2BOX', type: SourceType.MultiView },
		lowerThird: { sceneName: 'LAYER Graphics', sourceName: 'Lower Third', type: SourceType.Graphics },
		strap: { sceneName: 'LAYER Graphics', sourceName: 'Strap', type: SourceType.Graphics },
		ticker: { sceneName: 'LAYER Graphics', sourceName: 'Ticker', type: SourceType.Graphics },
		fullscreen: { sceneName: 'LAYER Graphics', sourceName: 'Fullscreen', type: SourceType.Graphics },
		fullscreenBrowser: { sceneName: 'Fullscreen GFX', sourceName: 'Browser', type: SourceType.Graphics },
		dsk: { sceneName: 'GFX', sourceName: 'TXT', type: SourceType.Graphics },
	},
}
