name: Node CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  pull_request:

jobs:
  lint:
    name: Typecheck and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          yarn
        env:
          CI: true
      - name: Run typecheck and linter
        run: |
          cd packages/blueprints
          yarn lint
          yarn build
        env:
          CI: true

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Prepare Environment
        run: |
          yarn
        env:
          CI: true
      - name: Run tests
        run: |
          cd packages/blueprints
          yarn test
        env:
          CI: true

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Prepare Environment
        run: |
          yarn
        env:
          CI: true
      - name: Run docusaurus
        run: |
          cd packages/docs
          yarn build
        env:
          CI: true
      - name: Publish
        if: github.ref == 'refs/heads/master' # always publish for just the master branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/build
